### ISSUE TITLE
大概看了一下，提个问题

### ISSUE THREAD

**Issue by vihuela** [AnotherJack/EasyEchoDemo#1]
写的很棒，大抵是View的id和bean的属性名称相关性通过遍历复制，是不是有俩场景可能不是很合适：
①仅仅需要部分赋值
②在使用DataBinding的场景

**Comment by AnotherJack** [comment]
第一个问题可以通过converter解决，给需要赋值的控件id加前缀或后缀来和不需要赋值的区分；
第二个问题，事实上，我从没实际用过DataBinding，对它的了解十分有限且仅停留在阅读资料的层面，所以暂时无法回答您这个问题，实在抱歉。

**Comment by vihuela** [comment]
谢谢老铁回答，nice
